# Generated by Django 4.2.4 on 2023-08-12 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    def insert_initial_data(apps, schema_editor):
        # Use the ORM to create instances of your models
        Role = apps.get_model('main_point_10', 'Role')
        Role.objects.create(name='Science Student')
        Role.objects.create(name='Commerce Student')
        Role.objects.create(name='Arts Student')

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RunPython(insert_initial_data), # added manually to run insert_initial_data
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=50)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_point_10.role')),
            ],
        ),
    ]
