# Generated by Django 3.2.5 on 2023-04-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Students',
                'db_table': 'student',
            },
        ),
    ]
