# Generated by Django 3.2.5 on 2023-04-06 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_fields', '0002_student'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('name', 'email', 'phone')},
        ),
    ]
