# Generated by Django 3.2.5 on 2023-04-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(choices=[('gujarat', 'Gujarat'), ('rajsthan', 'Rajsthan'), ('maharastra', 'Maharastra')], default='gujarat', max_length=100),
            preserve_default=False,
        ),
    ]
